In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set()

In [2]:
wine = pd.read_excel('http://taanila.fi/wine.xlsx')
wine.head()

Y     X1    X2    X3    X4   X5    X6    X7    X8    X9   X10   X11   X12  \
0  1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

    X13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
X = wine.drop('Y', axis =1)
y= wine['Y']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [5]:
from sklearn.linear_model import LogisticRegression

malli = LogisticRegression()
malli.fit(X_train, y_train)

y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

C:\Users\noora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\noora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [6]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_train_malli)

0.9849624060150376

In [7]:
accuracy_score(y_test, y_test_malli)

0.9111111111111111

In [8]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_train, y_train_malli))

[[39  1  0]
 [ 0 56  1]
 [ 0  0 36]]


In [9]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_test_malli))

[[18  1  0]
 [ 1 12  1]
 [ 0  1 11]]


In [10]:
winenew = pd.read_excel('winenew.xlsx')
winenew

X1    X2    X3    X4   X5    X6    X7    X8    X9   X10   X11   X12  \
0  14.19  1.59  2.48  16.5  108  3.30  3.93  0.32  1.86  8.70  1.23  2.82   
1  13.72  1.43  2.50  16.7  108  3.40  3.67  0.19  2.04  6.80  0.89  2.87   
2  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41  7.30  0.70  1.56   
3  12.70  3.87  2.40  23.0  101  2.83  2.55  0.43  1.95  2.57  1.19  3.13   
4  12.96  3.45  2.35  18.5  106  1.39  0.70  0.40  0.94  5.28  0.68  1.75   

    X13  
0  1680  
1  1285  
2   750  
3   463  
4   675

In [11]:
malli.predict(winenew)

array([1, 1, 3, 2, 3], dtype=int64)

In [12]:
malli.predict_proba(winenew)

array([[9.91864338e-01, 3.09789851e-09, 8.13565847e-03],
       [9.97739341e-01, 1.53427465e-05, 2.24531657e-03],
       [1.62488422e-03, 2.54458559e-04, 9.98120657e-01],
       [3.02109288e-04, 9.97829859e-01, 1.86803136e-03],
       [8.14217675e-03, 1.43078692e-02, 9.77549954e-01]])